PUBLICATION_FIELDS = [
    "publication_id",
    "work_group_id",
    "canonical_flag",
    "duplicate_of",
    "record_type",
    "source_record_id",
    "tool_name",
    "tool_alias",
    "title",
    "authors",
    "first_author",
    "corresponding_author",
    "doi",
    "pmid",
    "arxiv_id",
    "paper_url",
    "pdf_url",
    "publication_year",
    "venue",
    "publisher",
    "paper_type",
    "evidence_role",
    "abstract",
    "keywords",
    "task",
    "modality",
    "species",
    "technology",
    "dataset_names",
    "benchmark_included",
    "open_source_reported",
    "github_url",
    "license_reported",
    "citation_source",
    "citations",
    "citation_count_source",
    "source_url",
    "source_type",
    "extraction_method",
    "claim_text",
    "claim_span",
    "confidence",
    "trust_level",
    "review_status",
    "reviewed_by",
    "review_time",
    "kg_version",
    "embedding_version",
    "created_at",
    "updated_at",
    "last_checked",
    "notes",
    "human_review_decision",
    "canonical_scope",
    "evidence_category",
    "recommendation_eligible",
    "authority_tier",
    "audit_support_level",
]


BENCHMARK_FIELDS = [
    "benchmark_id",
    "work_group_id",
    "canonical_flag",
    "duplicate_of",
    "record_type",
    "source_record_id",
    "benchmark_name",
    "benchmark_version",
    "benchmark_type",
    "task",
    "subtask",
    "modality",
    "species",
    "technology",
    "dataset",
    "dataset_size",
    "batch_condition",
    "noise_condition",
    "tool_name",
    "tool_alias",
    "workflow_step",
    "metric",
    "metric_definition",
    "direction",
    "score",
    "normalized_score",
    "rank",
    "rank_scope",
    "n_tools_compared",
    "runtime",
    "memory_usage",
    "hardware",
    "statistical_significance",
    "paper_title",
    "paper_doi",
    "paper_pmid",
    "source_url",
    "source_type",
    "result_text",
    "claim_span",
    "evaluation_protocol",
    "reproducible",
    "code_available",
    "benchmark_repo",
    "extraction_method",
    "confidence",
    "trust_level",
    "review_status",
    "reviewed_by",
    "review_time",
    "kg_version",
    "created_at",
    "updated_at",
    "last_checked",
    "notes",
]


APPROVED_REVIEW_STATUSES = {"reviewed", "verified", "human_reviewed"}
REJECTED_REVIEW_STATUSES = {"rejected", "deprecated"}


def empty_record(fields: list[str]) -> dict[str, str]:
    return {field: "" for field in fields}
